# Generated by Django 3.2.23 on 2024-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('coords', models.CharField(max_length=254)),
            ],
        ),
    ]
