# Generated by Django 3.2.23 on 2024-02-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_quantity'),
    ]

    operations = [
        migrations.RenameField('Product', 'quantity', 'stock'),
    ]
